#:kivy 2.3.1

<VisionWidget>:
    FloatLayout:
        Image:
            id: camera_image
            size: root.size
            pos: root.pos

        Label:
            id: fallback_label
            text: "No Camera Feed"
            font_size: 32
            halign: "center"
            valign: "middle"
            size_hint: None, None
            size: root.size
            text_size: self.size
            pos: root.pos
            opacity: 1